### ISSUE TITLE
CMS Content > Resources Awaiting Publish

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#114]
**Description**

100s of resources have been reviewed, updated with images, probably by Chérie and Jamie? However the majority were not published means any changes are not currently being deployed to the live site.

It's very possible that this was due to the fact Jamie was not able to publish resources until later into the project (I think Chérie is still not able?)

In any case, these need to be worked through and published

**Considerations**

Do we want to get rid of the 'Changes are ready for review' process? Is this going to be practical over the long term?

**Comment by danlechambre** [comment]
@jkraesullivan if after discussing with @camillewortman - you want me to just publish everything that's currently in draft let me know - there looks to be 100s to work through otherwise.

As above, we might also want to consider removing the 'Ready for Review' toggle/process

**Comment by jkraesullivan** [comment]
@danlechambre just one clarification before @camillewortman decides. If a resource has a photo within it, there’s no way for you to mass publish just the photos correct? We want to make sure we decide resources before publishing but we’re thinking if there’s a way to mass publish just the photos that would be great- but I’m assuming we would need to publish the entire resource along with the photo.

**Comment by danlechambre** [comment]
Hey @jkraesullivan you're correct. I don't think there's a way to cherry pick parts of a document to publish such as the photo. A draft is simply "all of that changes since the last time it was published".

It's totally fine if there's still other things to work through/review before publishing - I just present mass publishing as one option to save time.

Could you clarify what you mean by "decide resources before publishing"?

**Comment by jkraesullivan** [comment]
Hey @danlechambre Okay great, that makes sense thanks for confirming. Sorry, that was my tired brain not explaining that very well, I meant to say "review resources before publishing" as in decide whether the resources are ready to be published or not, etc. I'll let Camille know what you relayed. Thanks again.

**Comment by danlechambre** [comment]
Everything was published manually - ready for review toggle was removed
