### ISSUE TITLE
CMS > regEx on 'website' url

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#45]
**Problem Statement**
Urls for websites should not _usually_ have a path after the domain name

**Suggested Solution**
Whilst content editors should still be able to to enter URLs with paths for websites - they should be warned in the Studio that this is more likely to be a resource than a website if it contains a path

**Acceptance Criteria**
User should receive a validation warning if the URL used on a 'website' document contains a path

**Comment by danlechambre** [comment]
@LeePNolan want a crack at this one? A small task whilst I'm getting everything into the backlog that needs to be done

**Comment by LeePNolan** [comment]
Sure. I have assigned myself.
