### ISSUE TITLE
CMS > Change Text on Website "Quoted..." Field

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#68]
**Problem Statement**
The "Quoted..." field in the `website` document type presently reads "some or all of the description text was taken directly from the source website". It has been determined that website descriptions will not be edited - therefore - removing the description and simply having "Description quoted from website" as the toggle title will be sufficient.

**Acceptance Criteria**
- Field should only have a title as above.
- Field Description should be removed.

**Comment by danlechambre** [comment]
@LeePNolan This is the task I was talking about. Just changing some text and removing a property so a nice one to get started with. Let me know if you need anything 🙌

**Comment by LeePNolan** [comment]
@danlechambre I have completed this and pull requested/merged - not sure if I was allowed but it all seemed to work! Guess it needs deploying now?
